### ISSUE TITLE
Peer review for assignment 2 - figalit

### ISSUE THREAD

**Issue by figalit** [STAT545-UBC-students/hw02-shreeramsenthi#1]
Peer-Review HW-02 for @shreeramsenthi  

Hey there, here are some general comments on your assignment, overall it was great!

**Remarks**

----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         | :heavy_check_mark:  | |  |
**Presentation: graphs**    |  :heavy_check_mark: |  | |
**Presentation: tables**    | :heavy_check_mark: |   |  |
**Achievement, creativity**  | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark:  |  |  |

- Usage of `levels` and `range` are a simple example that show you have done your studying!
- I really like that it's so easy to navigate through your homework,  definitely a great use of the markdown syntax and excellent code-commenting practices!
- Nicely labelled plots.

**Suggestions**
- I would suggest you check the bonus part in the assignment, more practice is always better!

**Comment by shreeramsenthi** [comment]
Hey, thanks for the super positive feedback. I think you're right that I should have done the bonus. I was busy with other things when I did the assignment, but I certainly agree that more practice is always good.

Thanks again!
