### ISSUE TITLE
Peer Review HW-02 for shreeramsenthi

### ISSUE THREAD

**Issue by singhg53** [STAT545-UBC-students/hw02-shreeramsenthi#2]
Peer-Review HW-02 for @shreeramsenthi
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         |  :heavy_check_mark: | |  |
**Presentation: graphs**    |  :heavy_check_mark: |  |  |
**Presentation: tables**    |  :heavy_check_mark: |   |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

Remarks:

- *Elaborate on above, esp. for "needs work."*
You have shown creativity and enjoyed reading your work. Please views comments below for more information.
- *Some specific praise?*
Great job. I really liked how you commented in between the code chunks. This is something I will use in the future.
- *Something I learned?*
I learned how to use the labs function properly, something I was having difficulty with.
- *Specific constructive criticism?*
I would ask you to try to push yourself to do more stuff beyond what was learned in class.

**Comment by shreeramsenthi** [comment]
Thanks for the kind feedback! I think you're right that I could do more. I've been a little lazy about the homework lately, but we're quickly getting into new territory for me, so I definitely need the practice.

Thanks again!
