### ISSUE TITLE
TA comments

### ISSUE THREAD

**Issue by hsmohammed** [STAT545-UBC-students/hw02-shreeramsenthi#3]
Hi Shreeram,

Thank you for this very organized homework submission. I just have some comments below.

# Reflection
Thanks for sharing your progress towards finalizing your homework.

# README.md file
You provided a very good README file that provide all the elements a reader to your repo needs.

# Data Exploration file
Thank you for the informative exploration markdown file. I just have a few comments below.
1- It is a good idea to provide a table of contents at the start of the file, especially if it is long. That can be achieved by editing the 'yaml' header as following.
```
output: 
  html_document:
    toc: true
```

2- Try to add description of each step before writing the code.

Thank you...

**Comment by shreeramsenthi** [comment]
Hey Mohammed, thanks for the feedback and the advice! I'll certainly give the toc a shot.

Cheers,
Shree
